#
# Jekyll configuration
#
auto: true
permalink: /:title
pygments: true
lsi: true
#markdown: rdiscount
#rdiscount
#  extensions: [smart]

#
# Site configuration
#
base_url: "http://pmiossec.github.com"	# L'URL de votre site
url: "http://pmiossec.github.com"	# L'URL de votre site
title: "Blog?"	# Titre de votre site
description: "Quelques infos..."	# La meta description sur la page d'accueil de votre site
author: "Philippe Miossec"	# Votre nom
email: "pmiossec+blog@gmail.com"	# Votre email
rss_feed: "/atom.xml"	# If you are using Feedburner, enter your feedburner address here.
#gauaid: ""	# Votre numéro de tracking Google Analytics


#
# Comments
#
disqusshortname: "pmiossec"	# Votre Shortname Disqus
#fb_appid: ""	# Votre ID d'application Facebook
#fb_comments: ""	# true pour activer les commentaires Facebook


#
# Socialize
#
socialize: "true"
socialize_twitter: "pmiossec" # Votre username Twitter
#socialize_googleplus: "" # Votre ID Google+
socialize_github: "pmiossec" # Votre username GitHub